name: reusable 
on: 
  workflow_call:
    inputs: 
      artifact-name:  
        description: name of deployable artifact file 
        required: false 
        default: dist 
        type: string 
    outputs:
      results:
        description: the result of the deployment operation 
        value: ${{jobs.deploy.outcome}}

jobs:

  deploy:
  outputs:
    outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      - name: set output result
        id: set-result
        run: echo "step-result=success " >> $GITHUB_OUTPUT
